package.json, src/lib/components/dateSelector/index.tsx
I reconfigured setting states to more specific points on input.
Updates were tested on other screens as well so existing screens should be fine.
The React compiler warnings while rendering and setting state on component are fixed as well.
=> DateSelector component bug fix

src/lib/components/cards/cardButton/index.stories.mdx, src/lib/components/cards/cardButton/index.tsx, src/lib/components/cards/index.tsx
This PR updates props table for `CardButton` storybook.
=> [CHA-2706] Update CardButton props and storybook

src/index.tsx, src/lib/components/segmentedControl/index.stories.mdx, src/lib/components/segmentedControl/index.tsx, src/lib/components/segmentedControl/style.module.scss, src/lib/index.tsx
This is the implementation of the Segmented Control component 👉 [Figma reference file](https://www.figma.com/file/MKs4cbojdVOBKUxv7okb93/Dirty-Swan-Design-System?node-id=234%3A13)
There's the possibility for a single lined segmented control and for a double lined segmented control. It's possible to navigate the component with the keyboard (using TAB and ENTER)
https://user-images.githubusercontent.com/3629231/130113286-1010c044-f875-499e-8bf1-202f102bd25e.mov
=> [CHA-2833] Create the SegmentedControl component

.github/pull_request_template.md
This PR adds the PR template of app and website to the DS repo
=> feat(git): [STO-4025] Add PR template to DS repo

Readme.md
Updating the README.MD release section
The Release section on README.MD was a bit confusing, this adds a more in-depth explanation on how to release
=> docs: Update README.MD Release section

src/lib/scss/public/grid.stories.mdx
Fixed docs on grid helper variables to make it consistent with the actual behavior
=> fix: breakpoint range docs

src/lib/index.tsx
* Adds markdown component export
Or give a reason why this does not apply: No visual changes
Or give a reason why this does not apply: No visual changes
=> fix(markdown): Add export for Markdown component

src/index.tsx
Adds another missing export 🙈
Or give a reason why this does not apply: No visual changes
Or give a reason why this does not apply: No visual changes
=> fix(markdown): Add missing export

src/lib/components/input/autoSuggestInput/style.module.scss
Fixes styling for suggestions list
Styling fix
=> [NoTicket] Fix styles for autoSuggestInput

src/lib/components/segmentedControl/index.test.tsx, src/lib/components/segmentedControl/index.tsx
* Add missing unique key property
* Add simple test to verify click and key down functionality
=> fix(SegmentedControl): [NoTicket] add key property

src/lib/components/autocompleteAddress/index.test.tsx, src/lib/components/autocompleteAddress/index.tsx, src/setupTests.js
Fixes the AutoCompleteAddress console warning. Add missing keys.
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen
```
=> fix(AutoCompleteAddress): [NoTicket] fix react warning

Readme.md, package.json, src/lib/components/input/currency/index.stories.mdx, src/lib/components/input/index.stories.mdx, src/lib/components/input/index.tsx, src/lib/components/input/style.module.scss, yarn.lock
* Add a new `Label` property to the Input component
=> feat(input): [NoTicket] Extend input

rollup.config.js
Ensure that source-maps are correctly resolved when in dev mode
=> fix(source-maps): [NoTicket] enable es sourcemaps to resolve correctly

.github/workflows/generate-release-draft.yml
Update action to work on workflow dispatch
=> tests(release-draft): [noticket] Update action to work on workflow dispatch

src/lib/util/generateId/index.ts
Adds an additional check for undefined window that was left out of https://github.com/getPopsure/dirty-swan/pull/184 by mistake. This doesn't run into any issues on dirty-swan checks but will run into server side run projects like the ones using nextjs.
=> fix(generateId): Add additional check for undefined window

src/lib/scss/private/base/_typography.scss
=> refactor(fonts): add missing fonts

src/lib/components/comparisonTable/components/TableArrows/style.module.scss, src/lib/components/comparisonTable/index.stories.mdx
Fix header buttons not clicking on mobile.
Added a button to header story to be able to test as well.
Solves:  
EMU-5875
=> fix(comparison table): [EMU-5875] Fix header buttons not clicking on mobile

src/lib/components/modal/bottomModal/index.tsx, src/lib/components/modal/bottomModal/style.module.scss, src/lib/components/modal/index.ts, src/lib/components/modal/regularModal/index.tsx, src/lib/components/modal/regularModal/style.module.scss
Update modal title to required as this is sometines not used and being passed as an empty string (`<Modal title="" />`).
Solves:  
EMU-5894
=> chore(modal):[EMU-5894] Update title to be optional

.github/pull_request_template.md
Add why this is needed section to PR template
=> docs(pull-request-template): [EMU-5970] Add why this is needed section to PR template

.github/pull_request_template.md, src/lib/scss/public/colors/default.scss, src/lib/scss/public/demo.tsx
Updates `grey-200` value
Solves:
[STO-5462](https://linear.app/feather-insurance/issue/STO-5462/swap-the-grey-200-color-globally)
=> feat(color): update grey-200 value

src/lib/scss/private/components/_cards.scss
Adds focus state to actionable card
Solves:
RVN-217
=> [RVN-217] Improve actionable card a11y

src/lib/components/dateSelector/index.test.tsx, src/lib/components/dateSelector/index.tsx, src/lib/hooks/useOnClickOutside.ts
Ensure that the calendar closes when clicking outside
=> Update calendar to close when clicking outside

src/lib/scss/index.scss, src/lib/scss/public/demo.tsx, src/lib/scss/public/shadows.scss, src/lib/scss/public/shadows.stories.mdx, src/shadows.scss
Add box-shadow classes and variables
Solves:
STO-5476
=> Add box-shadow classes and variables

src/lib/components/input/autoSuggestInput/index.tsx
Fix type of inputProps. This passed undetected because MDX does not show TS errors 👎 
This shouldn't be an issue anymore when we move to TS based stories.
=> fix(auto-suggest-input): Fix type of inputProps

src/index.tsx, src/lib/index.tsx, src/lib/util/images/index.stories.tsx, src/lib/util/images/index.ts
=> feat(images): Add images list export

src/lib/components/button/index.tsx
This PR fixes the type prop not being passed to button element.
=> fix(button): Fix type prop not being passed to button element

src/lib/index.tsx
This PR exports `InformationBoxProps`.
=> chore(information-box): Export InformationBoxProps

src/lib/components/input/currency/index.tsx
Update default currency input type
Solves:
EMU-7137
=> Change input type from string to number

src/lib/index.tsx
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> fix(card): Fix exported CardProps

.github/workflows/deploy.yaml
This PR attempts to fix the failing deployment step.
https://github.com/getPopsure/dirty-swan/actions/runs/9061459516/job/24893248647
=> fix(CI): [NoTicket] Fix deployment permissions

.github/workflows/deploy.yaml
This time, the real fix and removal of the temp workflow_dispatch
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> fix(CI): [NoTicket] Fix deployment permissions 2

.github/workflows/release.yaml
This PR fixes the failing release step:
https://github.com/getPopsure/dirty-swan/actions/runs/8879811926/job/24378442020
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> fix(CI): [NoTicket] Fix release permissions

.github/workflows/deploy.yaml
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> ci(deploy): Fix deploy version

.github/workflows/deploy.yaml
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> ci(deploy): Add 1.0.3 version to deploy action

.github/workflows/deploy.yaml
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> ci(deploy): Add missing environment to deploy action

.github/workflows/deploy.yaml
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> ci(deploy): Add missing environment url to deploy action

package.json, src/lib/components/markdown/config.ts, src/lib/components/markdown/index.stories.tsx, src/lib/components/markdown/index.tsx, src/lib/components/markdown/styles.module.scss, yarn.lock
This PR refactors the Markdown `component` making it use the latest packages and our combination of components on app and website.
Run storybook and [visit Markdown story](http://localhost:9009/?path=/docs/jsx-markdown--docs)
=> refactor(markdown): Refactor Markdown component

package.json
Adds react and react-dom as peer dependencies.
=> fix(peer-dependencies): Add react and react-dom as peer dependencies

src/lib/components/modal/genericModal/index.tsx
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> fix(modal): Make modal body full width

.github/workflows/deploy.yaml
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> ci(deploy): Deploy on workflow dispatch

src/index.tsx, src/lib/index.tsx
This PR adds the missing export for the Accordion component.
=> fix(accordion): Add missing accordion export

src/lib/components/accordion/index.tsx, src/lib/components/accordion/style.module.scss
This PR fixes the accordion animation behaving strangely.
=> fix(accordion): Fix accordion animation

babel.config.json, jest.config.js, package.json, src/index.tsx, src/lib/components/cards/card/index.tsx, src/lib/components/cards/card/style.module.scss, src/lib/components/icon/assets/zap-filled.svg, src/lib/components/icon/icons/ZapFilled.tsx, src/lib/components/icon/icons/index.ts, src/lib/components/table/components/TableCell/index.tsx, src/lib/components/table/components/TableCell/style.module.scss, src/lib/components/table/components/TableColumn/index.tsx, src/lib/components/table/components/TableColumn/style.module.scss, src/lib/components/table/components/TableContent/index.tsx, src/lib/components/table/components/TableContent/style.module.scss, src/lib/components/table/components/TableControls/index.tsx, src/lib/components/table/components/TableControls/style.module.scss, src/lib/components/table/components/TableSection/Collapsible.tsx, src/lib/components/table/components/TableSection/index.tsx, src/lib/components/table/components/TableSection/style.module.scss, src/lib/components/table/index.stories.tsx, src/lib/components/table/index.tsx, src/lib/components/table/style.module.scss, src/lib/components/table/utils/useScrollSync/index.ts, src/lib/components/table/utils/useTableNavigation/index.ts, src/lib/hooks/useMediaQuery.test.ts, src/lib/hooks/useMediaQuery.ts, src/lib/index.tsx, src/setupTests.js, yarn.lock
1.
2.
3.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
=> feat(table): [SIDE-349] Add Table component

src/lib/components/icon/IconWrapper/IconWrapper.tsx, src/lib/components/table/components/TableCell/index.test.tsx, src/lib/components/table/components/TableCell/index.tsx, src/lib/components/table/components/TableColumn/index.test.tsx, src/lib/components/table/components/TableContent/index.test.tsx, src/lib/components/table/components/TableControls/index.test.tsx, src/lib/components/table/components/TableControls/index.tsx, src/lib/components/table/components/TableSection/index.test.tsx, src/lib/components/table/index.stories.tsx, src/lib/components/table/index.test.tsx, src/lib/components/table/index.tsx, src/lib/components/table/utils/useScrollSync/index.test.tsx, src/lib/components/table/utils/useTableNavigation/index.test.tsx, src/lib/components/table/utils/useTableNavigation/index.ts
Add tests to Table component.
Solves:
SIDE-349
=> tests(table): [SIDE-349] Add tests to Table component

src/lib/components/modal/genericModal/index.tsx, src/lib/components/modal/index.stories.tsx, src/lib/components/modal/index.ts, src/lib/components/modal/regularModal/index.tsx, src/lib/components/modal/regularModal/style.module.scss
Minor style updates on modals as requested by the design team.
Solves
EPIC-533
=> refactor(modal): Minor modal style updates

src/lib/components/accordion/index.tsx, src/lib/components/accordion/style.module.scss
Minor accordion style updates (text-colors and bolds) as requested by the design team.
=> refactor(accordion): Minor accordion style updates

src/lib/components/modal/genericModal/index.tsx, src/lib/components/modal/hooks/useOnClose.ts, src/lib/components/modal/index.stories.tsx, src/lib/components/modal/index.ts
Add onModalScroll prop to Modal component.
=> refactor(modal): Add onModalScroll prop to Modal component

src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
This PR removes an unnecessary console log statement from the Table component
=> fix(table): remove console log statement

src/lib/components/table/Table.stories.tsx, src/lib/components/table/Table.tsx, src/lib/components/table/components/IconRenderer/IconRenderer.tsx, src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx, src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx, src/lib/components/table/components/TableCell/CTACell/CTACell.tsx, src/lib/components/table/components/TableCell/TableCell.module.scss, src/lib/components/table/components/TableContents/TableContents.module.scss, src/lib/components/table/components/TableContents/TableContents.tsx, src/lib/components/table/components/TableControls/TableControls.module.scss, src/lib/models/styles.ts
Full list of updates on the ticket:
https://linear.app/feather-insurance/issue/SIDE-634/comparison-table-updates-new-table-component
Solves:
SIDE-634
=> fix(table): [SIDE-634] Update table component

src/index.tsx, src/lib/index.tsx
=> chore(input-props): Export InputProps type

src/lib/components/table/Table.tsx, src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx, src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
Fix non DOM props being passed to DOM elements.
=> fix(table): Fix non DOM props being passed to DOM elements

src/lib/components/modal/genericModal/index.tsx
Add classnames support to modal title
=> fix(modal): Add classnames support to modal title

src/lib/components/modal/genericModal/index.tsx
Fixes scroll not working on FullScreenModal and RegularModal.
=> fix(modal): Fix scroll not working on FullScreenModal and RegularModal

src/index.tsx, src/lib/index.tsx
Export useMediaQuery hook from the package.
=> chore(hooks): Export useMediaQuery hook

src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
Fix unwanted space on header columns.
Solves:
SIDE-1063
1. Visit http://localhost:9009/iframe.html?args=&id=jsx-table--table-story&viewMode=story
2. Observe:
**Before:**
**After:**
=> fix(table): [SIDE-1063] Fix unwanted space on header columns

src/lib/components/table/Table.module.scss, src/lib/components/table/Table.tsx, src/lib/components/table/components/TableControls/TableControls.module.scss, src/lib/components/table/components/TableControls/TableControls.tsx
Reverts getPopsure/dirty-swan#412
=> Revert "fix(table): [SIDE-1316] Fix first row hidden on scrolling to  anchor"

src/lib/components/autocompleteAddress/index.stories.tsx, src/lib/components/autocompleteAddress/index.tsx
Update google maps api on component on country code update.
=> fix(autocomplete-address): Update country code

src/lib/components/autocompleteAddress/index.tsx, src/lib/components/badge/index.tsx, src/lib/components/segmentedControl/index.tsx, src/lib/components/segmentedControl/style.module.scss, src/lib/components/spinner/index.tsx
- Add a way to go back to search after manual entry
- Add role for better accessibillity
- Improve focus styles and allow navigating with space key
- Add aria properties
=> refactor(a11y): Update accessibility in components

src/lib/components/input/index.tsx
Add aria properties for invalid and error message, aria-invalid and aria-errormessage.
=> refactor(input): Add aria properties for invalid and error message

src/lib/components/comparisonTable/components/TableInfoButton/index.tsx
Add title/aria-label to table info button
=> refactor(table): Add title/aria-label to table info button

src/lib/scss/private/base/_typography.scss
Reverts getPopsure/dirty-swan#436
=> Revert "refactor(typography): Replace Merryweather with Mona Sans"

src/lib/scss/public/shadows.mdx, src/lib/scss/public/shadows.scss
=> feat(colors): [DES-2289] update shadows colors

src/lib/components/input/index.tsx, src/lib/components/input/input.stories.tsx, src/lib/components/input/stories/config.ts, src/lib/components/input/style.module.scss, src/lib/scss/private/components/_input.scss
Default state:
Hover state:
Focus state:
Filled default state:
Solves:
DES-2316
=> refactor(input): [DES-2316] Update input styles

src/lib/components/cards/card/style.module.scss, src/lib/components/cards/index.test.ts, src/lib/components/cards/index.tsx, src/lib/components/comparisonTable/components/AccordionItem/AccordionItem.module.scss, src/lib/components/comparisonTable/components/Chevron.tsx, src/lib/components/comparisonTable/components/Row/style.module.scss, src/lib/components/comparisonTable/components/TableArrows/style.module.scss, src/lib/components/comparisonTable/components/TableInfoButton/index.tsx, src/lib/components/comparisonTable/components/TableInfoButton/style.module.scss, src/lib/components/comparisonTable/components/TableRating/style.module.scss, src/lib/components/comparisonTable/components/TableTrueFalse.tsx, src/lib/components/comparisonTable/index.tsx, src/lib/components/comparisonTable/style.module.scss, src/lib/components/table/Table.module.scss, src/lib/components/table/Table.tsx, src/lib/components/table/components/TableCell/BaseCell/BaseCell.module.scss, src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx, src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.module.scss, src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx, src/lib/components/table/components/TableCell/TableCell.tsx, src/lib/components/table/components/TableContents/TableContents.module.scss, src/lib/components/table/components/TableContents/TableContents.tsx, src/lib/components/table/components/TableControls/TableControls.module.scss, src/lib/components/table/components/TableControls/TableControls.tsx
(buttons will be updated on their own)
Solves:
DES-2344
=> refactor(table): [DES-2344] Update table components styles

src/lib/components/cards/infoCard/index.stories.tsx, src/lib/components/cards/infoCard/index.tsx, src/lib/components/cards/infoCard/style.module.scss
Add icon and iconWithBackground variants:
=> refactor(info-card): Add icon and iconWithBackground variants

src/lib/components/accordion/index.tsx, src/lib/components/cards/card/index.stories.tsx, src/lib/components/cards/card/index.tsx, src/lib/components/cards/card/style.module.scss, src/lib/components/cards/cardButton/index.tsx, src/lib/components/cards/infoCard/index.tsx, src/lib/components/table/Table.tsx, src/lib/components/table/components/TableCell/CardCell/CardCell.tsx
**Before:**
**After:**
Solves:
DES-2406
=> refactor(cards): [DES-2406] Update card density naming and values
