getPopsure/dirty-swan

- src/lib/scss/private/base/_typography.scss
To have better accessibility, this PR adds a `focus` style to the p-a component
> [NoTicket] Add focus styles to p-a component

- src/lib/components/cards/cardWithTopIcon/index.stories.mdx
- src/lib/components/cards/cardWithTopIcon/index.tsx
- src/lib/components/cards/icons/index.ts
This PR is for a new variation of the `CardWithTopIcon` component.
There's a breaking change where the description of the component is now updated to solely React `children` components without any styles - this gives more freedom to style it at a higher level.
[See component in Figma](https://www.figma.com/file/582xiOgwHGIl4y5kGHrQ69/App?node-id=2277%3A0)
> Cha 2204 extend card component

- .github/workflows/deploy.yaml
- .github/workflows/release.yaml
This PR adds the following:
- Moving away from the `master` branch to the `main` branch (migration pending, will be done after merge)
- We can now directly release dirty-swan from GitHub by creating a "New Release" and tagging it accordingly. Personal NPMJS access will be also removed.
> [NoTicket] Created release workflow

- .github/workflows/deploy.yaml
- .github/workflows/release.yaml
- Readme.md
- package.json
This PR will update the way we're doing deployments moving forwards:
- No more master branch, it’s now renamed to main
- No more yarn release from your individual computers. You use the “draft a new release” feature from GitHub and beep boop, everything will be taken over by the CI 🤖 
- ⚠️  make sure the version is correctly set when creating a new release, i.e. `v2.0.1` (don’t forget the v). And for an alpha version that will be `v2.0.1-0` , `v2.0.1-1`…
> Use github-action for creating new releases

- src/lib/components/cards/a.stories.mdx
- src/lib/components/cards/cardWithTopLeftIcon/index.stories.mdx
- src/lib/components/cards/cardWithTopLeftIcon/index.tsx
- src/lib/components/cards/cardWithTopLeftIcon/style.module.scss
- src/lib/components/cards/index.tsx
- src/lib/scss/public/colors/default.scss
- src/lib/scss/public/demo.tsx
This PR adds a new `xsmall` version of the top left card component [specified here](https://www.figma.com/file/MKs4cbojdVOBKUxv7okb93/Dirty-Swan-Design-System?node-id=358%3A19) and used inside the comparison table component.
**I'm not entirely sure if I have to do the PR to the new `main` branch or `master`.*
> [CHA-2147] Add xsmall size to top left icon card component

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/index.stories.mdx
- src/lib/components/modal/index.ts
- src/lib/components/modal/regularModal/index.tsx
This PR solves [CHA-2428](https://linear.app/feather-insurance/issue/CHA-2428/fix-spacing-in-the-price-details-modal)
**What changed?**
- The Modal component now has a `className` prop to allow more style flexibility
- The scroll is being blocked by an event and not by hiding the scrollbar. This was done to prevent a jump when the modal was open:
Before:
After:
**Caveats:**
- This new implementation only prevents the mouse wheel event. So scrolling with keyboards (space, up, and down keys) is still possible. We can go further and prevent scrolling using the keyboard but I feel that it's not necessary at this point.
- If the modal is bigger than the window, scrolling is not possible.
> [CHA-2428] add className prop to Modal component

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/index.stories.mdx
- src/lib/components/modal/index.ts
- src/lib/components/modal/regularModal/index.tsx
This PR adds the following functionality:
- Adds a new `required` prop to prevent the user from closing the modal
- Adds a new `touchmove` event handler to prevent scroll on mobile devices
- Moves all the component logic to the `useOnOpen` hook to share it with the different modals
> [CHA-2532] add required prop to allow closing the

- src/index.tsx
- src/lib/components/comparisonTable/index.stories.mdx
- src/lib/components/comparisonTable/index.tsx
- src/lib/components/comparisonTable/style.module.scss
- src/lib/components/input/autoSuggestMultiSelect/index.tsx
- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/index.stories.mdx
- src/lib/components/modal/index.ts
- src/lib/components/modal/regularModal/index.tsx
- src/lib/index.tsx
This PR does the following:
- Fixes a typo in the `dismissible` modal prop and updates modal documentation
- Removes the `default` export in the ComparisonTable component.
- Adds a new `styles` prop to the `<ComparisonTable />` component to allow style overrides
> [CHA-2539] Update modal documentation

- src/lib/components/cards/cardWithLeftIcon/index.tsx
- src/lib/components/cards/cardWithTopIcon/index.stories.mdx
- src/lib/components/cards/cardWithTopLeftIcon/index.tsx
- src/lib/components/cards/infoCard/index.tsx
This PR updates the description color of the card component
Before:
After:
> [CHA-2393] Update description color on info cards

- src/lib/components/chip/style.module.scss
- src/lib/components/modal/regularModal/style.module.scss
This PR is tiny, but it adds the `-moz-fit-content` value to some `width` properties in the Modal and Chip components.
This is necessary to make this property work on Firefox. And right now it's causing style inconsistencies in some modals.
> [NoTicket] add prefix to fit-content width value to support Firefox

- src/lib/components/input/autoSuggestInput/index.stories.mdx
- src/lib/components/input/autoSuggestInput/index.tsx
- src/lib/components/input/autoSuggestInput/style.module.scss
- src/lib/components/input/autoSuggestMultiSelect/index.stories.mdx
- src/lib/components/input/autoSuggestMultiSelect/index.tsx
This PR adds a new prop to the Autosuggest component that allows the dropdown text to be wrapped:
> [EMU-3211] add new prop to control text wrapping on autosuggest dropdown

- src/lib/scss/public/grid.scss
This PR reverts the variable used in the `p-size-tablet` media query
> [No ticket] remove responsive utilities

- src/lib/scss/private/_reset.scss
These elements were missing in the CSS reset and so among other things, rule 'font:inherit;' wasn't applied. This led to some inconsistencies when using the elements without additional CSS classes - most notably the "Products" button on the homepage not inheriting 'Lato' but using the OS fallback font instead
.
> [NoTicket]: fix: add inputs and buttons to CSS reset

- src/App.tsx
- src/lib/components/cards/a.stories.mdx
- src/lib/components/cards/cardWithLeftIcon/index.stories.mdx
- src/lib/components/cards/cardWithLeftIcon/index.tsx
- src/lib/components/cards/cardWithLeftIcon/style.module.scss
- src/lib/components/cards/cardWithTopIcon/index.stories.mdx
- src/lib/components/cards/cardWithTopIcon/index.tsx
- src/lib/components/cards/cardWithTopLeftIcon/index.stories.mdx
- src/lib/components/cards/cardWithTopLeftIcon/index.tsx
- src/lib/components/cards/index.tsx
This PR implements the missing "xsmall" variant of the CardWithLeftIcon component to match the corresponding checkbox component.
It also includes, among some minor refactors, a breaking change as it changes the current card prop "titleSize" to "cardSize" to better reflect the intent and effect. 
The xsmall card variant is needed to be able to use a card on roughly the same level of importance as paragraph text.
'titleSize' in a lot of cases not only changes the title size but also other attributes such as padding and margin, so this is why the prop renaming was deemed necessary.
Solves:  
STO-3386 
> feat(CardWithLeftIcon): [STO-3386] implement missing xsmall card variant

- src/lib/components/cards/cardWithLeftIcon/index.tsx
- src/lib/components/cards/cardWithLeftIcon/style.module.scss
This PR adds the missing whitespace between card title and text to make the design consistent with the Figma file.
Solves:  
STO-3497 
> fix(CardWithLeftIcon): [STO-3497] Add whitespace between title and text

- src/lib/scss/private/components/_buttons.scss
This PR fixes the spacing on the CSS and JSX versions of the buttons by updating the
p-btn class padding to match the values of the Figma design.
Design:
Updated button:
To have consistent button styles across all of the feather products.
Solves:  
EMU-3904 
> fix(p-btn): [EMU-3904] Update p-btn spacing to match Figma design

- src/lib/scss/private/base/_display.scss
- src/lib/scss/private/base/_spacing.scss
- src/lib/scss/private/base/display.stories.mdx
- src/lib/scss/private/base/spacing.stories.mdx
- src/lib/scss/private/components/_buttons.scss
This PR adds 3 new utility classes `.gap`, `.c-gap` and `.r-gap` to enable the use of the properties `gap`, `column-gap` and `row-gap` without the need for custom css.
It also adds the missing `.d-grid `class.
To be able to use gaps without having to resort to custom CSS.
Solves:  
EMU-3910 
> feat(Spacing): [EMU-3910] Add gap utility classes to DS

- src/lib/scss/public/colors/default.scss
- src/lib/scss/public/demo.tsx
This PR adds 3 new color families: glacier, spearmint and pink
Solves:  
EMU-3942 
> feat(Colors): [EMU-3942] Add glacier, spearmint and pink color families

- src/lib/scss/private/components/_buttons.scss
When updating the buttons with the proper paddings the text was no longer centered which was counteracted by using flex to center the text. But the root cause was actually the incorrect line-height. 
When the line-height is removed the text is centered without the need for flex. This avoids visual regressions due to manually set display: inline-block or block in the other parts of the codebase.
> fix(Buttons): [EMU-4003] Remove incorrect line-height and superfluous flex attributes

- src/lib/scss/private/components/_buttons.scss
This PR fixes an issue where the missing line-height would lead to off center text in some edge cases.
> fix(Buttons) [EMU-4007] add explicit line height to ds button

- src/lib/scss/private/components/_buttons.scss
This PR sets the line-height to a fixed value to fix an issue where anchor tags using button classes would have text that is slightly off center.
> fix(Buttons): [NoTicket] Set line-height to a fixed value

- package.json
Currently only the dist folder is included in the package which makes react-scripts 5.0 show 51 warnings after the planned version bump in the app repo.
Adding the src folder to package.json's "files" should get rid of this issue:
https://github.com/facebook/create-react-app/discussions/11767#discussioncomment-2096794
> fix(npm): [STO-3642] Add src folder to package.json's tracked files

- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/index.stories.mdx
- src/lib/components/modal/regularModal/style.module.scss
1. This PR fixes a bug that was allowing users to open modals when pressing the `ESC` key
2. It also fixes the  dependency array on `useOnClose.ts` hook
We want the modals to execute the `onClose` function only when the modal is open.
Solves:  
EMU-4306
No visual changes
No visual changes
N/A
> fix(modal): [EMU-4306] do not open modal when pressing the esc key

- package.json
- src/lib/components/autocompleteAddress/index.tsx
- src/lib/components/autocompleteAddress/util/index.ts
- yarn.lock
We're updating to public-model in order to take advantage of the ESM module definition
- The dist/index.js file size was 3MB 😱 now it is 733KB
- NextJS12 now supports ESM, it's now safe to have all our libraries exported as ESM.
> chore: Updating @popsure/public-model to 1.0.1

- src/lib/scss/private/_reset.scss
This PR hides the input number arrows when using Firefox. The arrows were already hidden for Chrome / Webkit / Opera based browsers but a corresponding CSS rule for Firefox was missing.
BEFORE:
AFTER:
_Please include additional context of why this PR is necessary._
Solves:  
STO-4003
STO-4195
> fix(Input): [STO-4003] Hide input number arrows in Firefox

- src/lib/components/autocompleteAddress/demo.tsx
- src/lib/components/autocompleteAddress/index.stories.mdx
- src/lib/components/autocompleteAddress/index.tsx
- src/lib/components/autocompleteAddress/style.module.scss
- src/lib/components/dateSelector/index.stories.mdx
- src/lib/components/dateSelector/index.tsx
1.  Fixes the uneven widths for the `AutocompleteAddress` on mobile
**BEFORE:**
**AFTER:**
2. Exposes placeholder text and other props to make `AutocompleteAddress` and `DateSelector` components localizable
3. Updates the docs
Solves:  
STO-4281  
STO-3809  
> feat(localization): [STO-4281] Expose props to enable localization

- src/lib/components/autocompleteAddress/style.module.scss
This PR adds` !important` to the CSS rule that removes the width constraints of the house number input field to fix an issue where the rule would not stick in all cases.
Due to the erratic import order of CSS and the fact that both the CSS module class `.house-number-input` and utility class `.wmx2` have the same specificity, there are cases where the rule to remove the constraints cannot take effect.
To consistently have the house number input span the whole width on mobile-size screen sizes.
> fix(AutocompleteAddress): [NoTicket] Make removing max-width !important

- src/lib/components/multiDropzone/icons/upload.svg
- src/lib/components/multiDropzone/index.stories.mdx
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/style.module.scss
Updates Multidropzone component to align with Figma designs
We want to align DS components to updated versions on Figma
Solves:  
STO-4286
> [STO-4286] Refactor multidropzone to align Figma designs

- src/lib/components/dateSelector/datepicker.scss
- src/lib/components/input/index.stories.mdx
- src/lib/components/input/style.module.scss
- src/lib/components/multiDropzone/UploadFileCell/style.module.scss
- src/lib/components/signaturePad/style.module.scss
- src/lib/scss/private/base/style.module.scss
- src/lib/scss/private/components/_badge.scss
- src/lib/scss/private/components/_buttons.scss
- src/lib/scss/private/components/_input.scss
- src/lib/scss/public/colors/default.scss
- src/lib/scss/third-party/_google_places.scss
1. Rename the current Grey 300 to Grey 400
2. Create a new Grey 300 at #EDEDF2
3. Update Grey-500 to #848490
TableRowHeader (@app)
Download complete state
MultiDropzone
SegmentedControl with subtitle
Signaturepad
Outline grey button
Outline grey button (hovered)
`grey-500` on Disabled Input will be removed for STO-3198
Solves:  
STO-3198  
> feat: [STO-3198] update neutral colors

- src/lib/components/input/index.tsx
- src/lib/components/input/style.module.scss
Fix input prefix color on disabled state to grey-600
Solves:
STO-3197
> fix: [STO-3197] change input prefix color to grey-600 when it's disabled

- src/lib/scss/public/colors/default.scss
Change `grey-500` value to #91919C after design review
Solves:  
STO-3198
> feat: [STO-3198] change grey-500 color to #91919C

- package.json
- src/lib/components/multiDropzone/index.tsx
- yarn.lock
1. Refactors Multidropzone component to collect multiple files at once
2. Adds `maxFiles` prop to the component to give control of how many files can be uploaded
3. Adds a generic error display to the component when user tried to upload more files than allowed.
‼️ Note: This component should be refactored again to unify all errors. Currently, file size and invalid file type errors are handled on BE and therefore omitted from defining the error inside this component.
We want to allow customers to upload multiple files at once
Solves:  
STO-4342
> [STO-4342] Refactor Multidropzone to collect multiple files at once

- src/lib/scss/private/components/_badge.scss
- src/lib/scss/private/components/badge.stories.mdx
Added a purple color variant to badge component scss.
This update will be needed in website [ImageWithText slice PR](https://github.com/getPopsure/website/pull/763)
It is a common use case of badge in website like below:
> feat: add a default color variant to badge component

- src/lib/components/dateSelector/datepicker.scss
- src/lib/components/dateSelector/index.tsx
1. Fixes widths of dates on day picker
2. Closes day picker pop up when date is chosen on selector
We want the date component to align with Figma designs
> Noticket date comp fix

- src/lib/components/comparisonTable/components/AccordionItem/AccordionItem.tsx
- src/lib/components/comparisonTable/index.tsx
This PR changes the `AccordionItem` subcomponent to accept JSX in addition to strings as a label and removes the separate `iconSrc` prop as it is no longer needed.
> feat(ComparisonTable): [NoTicket] Add support for JSX in labels

- src/lib/components/comparisonTable/index.tsx
This PR fixes the accordion mechanisms by providing a proper id after the recent changes that allowed JSX labels.
> fix(ComparisonTable): [NoTicket] Fix accordion

- src/lib/components/multiDropzone/index.stories.mdx
- src/lib/components/multiDropzone/index.tsx
This PR adds i18n capabilities to the MultiDropzone component by exposing text override properties.
To be able to localize the component.
> feat(MultiDropzone): [NoTicket] Add i18n capabilities

- src/lib/components/input/autoSuggestInput/style.module.scss
Fixes Autosuggest suggestions list positioning
This fixes the width of the container
> [NoTicket] Update Autosuggest component suggestion list width

- src/lib/scss/private/components/_input.scss
Added padding right to `p-label--bordered`
As-is
To-be
Long text that stretches the button needs a padding
Solves:  
[STO-4942](https://linear.app/feather-insurance/issue/STO-4942/the-buttons-in-calculator-need-to-accommodate-long-german-words)
> fix(button): [STO-4942] add padding right to bordered input

- src/lib/components/input/style.module.scss
Remove unnecessary margins for the label in the Input component 
> feat(input): [NoTicket] fine-tune label input styling

- src/lib/components/comparisonTable/components/TableArrows/index.tsx
- src/lib/components/comparisonTable/components/TableArrows/style.module.scss
- src/lib/components/comparisonTable/index.tsx
- Fixed misaligned header buttons and title of `ComparisonTable` mobile
- Added missing key to div mapping to remove console warning
**AS-IS**
**TO-BE**
For website [PR](https://github.com/getPopsure/website/pull/887) on `ComparisonTable`
> fix(comparison-table): [no-ticket] fix mobile spacing for table header

- package.json
- src/lib/components/input/index.tsx
- yarn.lock
Make the generated input id stable and use a simple id generation approach, as the id only has to be unique at render time.
* Drop the uuid dependency 
>  fix(input): [NoTicket] add stable id to input

- src/lib/components/input/currency/index.stories.mdx
- src/lib/components/input/index.tsx
- src/lib/components/input/style.module.scss
- src/lib/scss/utils/_index.scss
Update input to use sr-only class on hidden label. 
This PR also adds the `.sr-only` class to dirty-swan utils.
The `sr-only` class is based on several utils and accessibility recommendations:
https://tailwindcss.com/docs/screen-readers
https://a11y-guidelines.orange.com/en/articles/accessible-hiding/
> refactor(input): [no-ticket] update input to use sr-only class on hidden label

- package.json
- src/lib/components/multiDropzone/UploadFileCell/index.tsx
- src/lib/components/multiDropzone/index.stories.mdx
- src/lib/components/multiDropzone/index.test.tsx
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/types.ts
- src/lib/components/multiDropzone/utils.ts
- src/lib/components/multiDropzone/utils/index.test.ts
- src/lib/components/multiDropzone/utils/index.ts
- src/setupTests.js
- yarn.lock
Add accept filetype validation support to MultiDropZone component.
1. Adds support to accept prop on MultiDropZone component, including helper states of `document` and `image`
2. Refactors component to have a separated file for utils and types
3. Supports showing file errors both inline and as a general state
4. Adds textOverrides support to error messages from react-dropzone
Solves:  
EMU-3320
https://user-images.githubusercontent.com/4015038/215064138-3886a175-eaf8-408b-8a6b-3d4faabbd12f.mov
> refactor(multidropzone): [EMU-3320] Add accept filetype validation support

- src/lib/components/multiDropzone/index.stories.mdx
- src/lib/components/multiDropzone/index.test.tsx
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/types.ts
- src/lib/components/multiDropzone/utils/index.ts
- src/lib/util/formatBytes/index.test.ts
- src/lib/util/formatBytes/index.ts
Add file maxSize validation support to MultiDropZone component.
1. Added support to maxSize prop and internal validation of size
2. Added formatBytes util to show more human readable information on file size
Solves:  
EMU-5671
> refactor(multidropzone): [EMU-5671] Add file maxSize validation support

- src/lib/components/input/index.tsx
Use uuid to generate the input fallback id.
> refactor(input): [no-ticket] use uuid for id generation

- package.json
- rollup.config.js
- tsconfig.cjs.json
- tsconfig.esm.json
- tsconfig.json
This is an initial approach to enable consuming apps to tree-shake ds correctly.
To help tree-shake optimized apps, we will need to make some changes:
* `package.json` needs to define an esm specific entry point, this can be achieved by defining `module`.
* `package.json` needs a defined `sideEffects` which excludes css to ensure that the the library can be tree-shaked.
* Create an `esm` build that is isolated from the `cjs` build.
* Set the `TypeScript` output directory to the `esm` build folder to enable consuming applications to find the types.
These are first steps to get to a minimal bundle size when working with ds.
To `test` the changes, the following approach is required:
* Create a controlled environment, f.e. using vite and the react-ts template to setup a barebones app
* Run …
> fix(tree-shaking): [NoTicket] enable tree-shaking

- .github/release-drafter.yml
- .github/workflows/generate-release-draft.yml
Add github action for generating release drafts on PR being merged to main.
**Note:** Tests seem to be failing because of missing `.github/release-drafter.yml` file on default branch but it is included on this PR as well so should be working on main. If needed we can add the files in two separate PRs.
> feat(github workflow): [noticket] Add github action for generating release drafts

- src/index.tsx
- src/lib/components/comparisonTable/components/TableButton/index.test.tsx
- src/lib/components/comparisonTable/components/TableButton/index.tsx
- src/lib/components/comparisonTable/components/TableButton/style.module.scss
- src/lib/components/comparisonTable/components/TableRowHeader/index.test.tsx
- src/lib/components/comparisonTable/components/TableRowHeader/index.tsx
- src/lib/components/comparisonTable/index.stories.mdx
- src/lib/components/comparisonTable/index.tsx
- src/lib/index.tsx
1. Adds TableButton component and exports it
2. Hides icon span when icon is not passed to TableRowHeader
3. Updates TableRowHeader to use TableButton instead of TableInfoButton
4. Adds tests to TableButton and TableRowHeader component
5. Adds an example of TableRowHeader and TableButton components to ComparisonTable story, as shown on the screenshot below
_Please include additional context of why this PR is necessary._
Solves:  
[EMU-5713](https://linear.app/feather-insurance/issue/EMU-5713/update-comparisontable-component-styles)
> refactor(comparison table): [EMU-5713] Add TableButton to TableRowHeader component

- src/index.tsx
- src/lib/components/multiDropzone/types.ts
- src/lib/index.tsx
Removed uploaded as this value is not used anymore.
This also adds MultiDropzone types to be exported from lib index file.
> fix(multidropzone): [noticket] Remove unused uploaded filetype and export types

- src/lib/components/comparisonTable/components/Row/style.module.scss
- src/lib/components/comparisonTable/index.stories.mdx
Fix comparison table addon to be full width. 
Since `.cell` styles had an `h4` preffix, it was needed to add the same preffix to addon as well so that styles weren't overriden.
This PR also fine tunes the addon width styles.
> fix(comparison table): [noticket] Fix addon to be full width

- src/lib/components/comparisonTable/components/TableButton/index.tsx
- src/lib/components/comparisonTable/components/TableButton/style.module.scss
- src/lib/components/comparisonTable/components/TableRating/index.tsx
- src/lib/components/comparisonTable/components/TableRowHeader/index.tsx
- src/lib/components/comparisonTable/index.stories.mdx
Adds children type to TableButton component explicitely as in some versions of react, children doesn't exist on React.FC type causing a typescript error.
Fixes underlined styles for TableButtonHeader component when multiline. Still needs to be kept as a border because on non text underline behaviour.
**Before**
**After**
> fix(table button): [noticket] Fix types and underlined styles

- package.json
- src/lib/components/input/index.tsx
- src/lib/components/multiDropzone/index.tsx
- src/lib/util/generateId/index.test.ts
- src/lib/util/generateId/index.ts
- yarn.lock
Replaces uuid package with a custom and simpler generateId util.
uuid package can't be tree-shaked and was adding a giant additional size to repos where it was being imported.
Usually, using random for random ids is not the most efficient way but since this ids are not persistent and used for runtime only (generate label/input ids, temporary ids for error entries) this downgrade from uuid might make sense.
Named the util generateId so it doesn't suggest it is a fully and standardised uuid and replaces the function.
The id generated is based on a random number that is then parsed into an hex string for each of the characters.
> refactor(uuid): [noticket]: Replace uuid package with generateId util

- .github/workflows/tests.yaml
Set fixed `v16.10.0` version of node when running `test-build-storybook`.
Current PRs were[ failing when building storybook](https://github.com/getPopsure/dirty-swan/actions/runs/4231087840/jobs/7349172627) since github actions were somehow using node v17 instead of the ones used previously. No changes were made before to trigger this error.
> fix(test-build-storybook): Set fixed version of node

- .github/workflows/deploy.yaml
- .github/workflows/tests.yaml
Set fixed `v16.10.0` version of node when running `deploy-storybook-to-gh-pages`.
Why is this needed?
Current deploy is [failing when deploying storybook](https://github.com/getPopsure/dirty-swan/actions/runs/4232126452) since github actions were somehow using node v17 instead of the ones used previously. No changes were made before to trigger this error.
Solves:  
STO-XXX  
EMU-XXX
> fix(deploy-storybook): Set fixed version of node

- src/lib/components/comparisonTable/components/Row/style.module.scss
- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
This PR updates the default header width size from 0 to 1400.
This doesn't break any layout as there are resize observers updating to the final size. However, this improves the initial rendering making the content not glitch/jump since 1400 is closer to 100% than 0 and content shouldn't grow over 100% of viewport anyway. The purpose of this is to fix flaky tests. Not using window width since it breaks on SSR.
> fix(comparison table): Update default header width size

- src/lib/scss/private/base/_typography.scss
- src/lib/scss/public/font/default.scss
Switch from @import to @font-face when loading fonts to prevent blocking
> refactor(fonts): switch from import to font-face

- src/lib/scss/public/font/default.scss
> refactor(fonts): add missing font weights

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/regularModal/index.tsx
- src/lib/components/modal/regularModal/style.module.scss
Fixes overlay area so that all clicks outside body close the modal (including margin). Also fixes if dismissable, making it not closable on overlay click.
Adds a bigger margin for bigger modals, so that they don't show over navbar. This only impacts modals with height bigger than window height.
**Note:** While this should be a zIndex fix on navbar side, it's an easy way to fix without impacting other content and adding a nice margin to content. Should still be checked on the other side of the application.
**Before:**
**After:**
_Please include additional context of why this PR is necessary._
> fix(modal): Fix margin and overlay area

- src/lib/components/input/currency/index.test.tsx
- src/lib/components/input/currency/index.tsx
Fix currencyInput selectionStart after value format, making the cursor stay in the expected position instead of going to the end of the input.
Solves:  
EMU-5966
https://user-images.githubusercontent.com/4015038/227987170-270f8522-dadb-4956-ab79-a21393561529.mov
> fix(currency-input): [EMU-5966] Fix currencyInput selectionStart after value format

- src/lib/scss/private/components/_buttons.scss
* Adds space before outline in focus state of button
Solves:
RVN-212
> feat(button): [RVN-212] Add spacing before outline in focus state

- src/lib/components/comparisonTable/components/TableInfoButton/index.tsx
- src/lib/components/comparisonTable/components/TableInfoButton/style.module.scss
Make TableInfoButton focusable.
Solves:
EMU-6047
Non focused state:
Focused state:
> fix (table-info-button): [EMU-6047] Make TableInfoButton focusable

- src/lib/components/comparisonTable/components/TableInfoButton/index.tsx
Related to https://github.com/getPopsure/dirty-swan/pull/209. This made the component focusable but since it's not a default browser button, it doesn't allow to trigger using keyboarding only which is a far from optimal user experience.
Solves:
EMU-6047
> fix(table-info-button): [EMU-6047] Make TableInfoButton click happen on enter

- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
This prevents scrolling on table to update tab index on above mobile breakpoints. This means that on resize, we always have a same consistent result. This is specially important for visual regression testing as resizing the page would show the current tab randomly.
> fix(comparison-table): Prevent scroll to update tab index on above mobile breakpoints

- src/lib/components/modal/bottomModal/style.module.scss
Add bottom padding to BottomModal component. This adds an extra div so that when manual padding is set (which is currently happening, this spacing is always there).
On mobile there are some widgets (like intercom) that are over the modal component text.
Solves:
EMU-5924
Before:
After:
> refactor(bottom-modal): [EMU-5924] Add bottom padding to BottomModal

- package.json
- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
- src/lib/components/comparisonTable/index.tsx
- yarn.lock
Update react-scroll-sync to v0.11.0 which uses the new context API.
This should fix the rendering issues on visual regression tests.
> chore(comparison-table): Update react-scroll-sync to v0.11.0

- src/lib/components/input/autoSuggestInput/index.stories.mdx
- src/lib/components/input/autoSuggestInput/index.tsx
Allow to pass input props to AutoSuggestInput.
This can be useful, as an example, to set autocomplete property off.
Pass a valid HTML input prop and see that it's rendered on the input component.
> refactor(auto-suggest-input): Allow to pass input props to AutoSuggestInput

- src/lib/components/comparisonTable/components/Row/style.module.scss
Fix comparisonTable maxWidth on mobile, which doesn't trigger on mobile devices. This seems to be only visible on website, not on storybook.
`Spotted this issue on public LP on mobile. The name appears after scrolling horizontally a bit `
> fix(comparison-table): Fix comparisonTable maxWidth on mobile

- src/lib/components/input/checkbox/index.tsx
- src/lib/components/input/checkbox/styles.module.scss
Fix checkbox max width on mobile (rookie mistake 😅 ).
**Before:**
**After:**
> fix(checkbox): Fix max width on mobile

- src/lib/components/input/checkbox/index.tsx
- src/lib/components/input/checkbox/styles.module.scss
Update checkbox to use max-width instead of width.
While nothing major changes, this ensures stability with previous styles of checkbox meaning no visible changes from previous usage.
> fix(checkbox): Update checkbox to use max-width instead of width

- src/lib/scss/public/colors/default.scss
- src/lib/scss/public/demo.tsx
Updates `primary-100` and `purple-100` color value
Solves:
[CHA-3977](https://linear.app/feather-insurance/issue/CHA-3977/change-p100-color-globally)
> feat(color): [CHA-3977] update color p-100 value

- src/index.tsx
- src/lib/components/link/index.stories.tsx
- src/lib/components/link/index.tsx
- src/lib/index.tsx
This PR adds the `Link` component to dirty swan.
Solves:
EMU-5965
Run `yarn storybook` and go to [Link story](http://localhost:9009/?path=/docs/jsx-link--link-story)
> feat(link): [EMU-5965] Add Link component

- src/lib/components/chip/index.tsx
- src/lib/components/input/autoSuggestMultiSelect/index.tsx
- src/lib/components/input/autoSuggestMultiSelect/style.module.scss
Add entry animation to chip container. This will be revisited once we have transition/animation pritives/utilities.
CHA-3762
https://github.com/getPopsure/dirty-swan/assets/4015038/d3387e94-e0b1-4ff9-b44b-f98471539bd1
> refactor(auto-suggest-multi-select): [CHA-3762] Add entry animation to chip container

- src/lib/components/cards/cardWithLeftIcon/index.stories.tsx
- src/lib/components/cards/cardWithLeftIcon/index.tsx
Update CardWithLeftIcon:
- allow customisation of left icon size
- add subtitle
- make subtitle optional
> refactor(card-left-icon): Update CardWithLeftIcon icon size and text

- src/lib/components/input/currency/index.tsx
This PR fixes an issue with the `CurrencyInput` component that makes it run its `onChange` handler on initial render. 
Currently, if your code relies on checking if the value is in an `undefined` state initially (when no value was entered yet), it will be overwritten with `0` on first render and while there still won't be any value in the input, internally the value is already `0`. This breaks the logic on private LP calculator for example and will show "you are not eligible" prematurely.
Solves:
EMU-6492
> fix(CurrencyInput): [EMU-6492] Don't exec onChange on initial render

- src/lib/components/icon/IconWrapper/IconWrapper.tsx
This PR removes the default color from IconWrapper component as the icons should show parent elements color by default.
> fix(icon-wrapper): Remove default color from icon wrapper

- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
- src/lib/components/comparisonTable/index.tsx
This PR fixes comparison table not setting ref on load.
This is a **temporary solution as react-scroll-sync isn't maintained anymore**. 
There is an active issue in the repo that fixes our needs https://github.com/okonet/react-scroll-sync/issues/79 and we should be able to use ref and not IDs once this is released.
Go to a comparison table component on mobile, hard refresh and click on the right arrow (it will only work after you swipe on the content). 
This happens because onSync only triggers after scrolling changes and not on load and the way react-scroll-sync works, we cannot use refs for internal divs 😭 
> fix(comparison-table): Fix comparison table not setting ref on load

- src/lib/scss/private/components/_input.scss
1. Updates the bordered checkbox component's vertical padding (from `8px` to `12px`)
2. This change is also reflected on the CSS radio button component since it also uses the `p-label--bordered` class.
Current:
Updated:
Solves:
[EMU-4092](https://linear.app/feather-insurance/issue/EMU-4092/update-padding-on-checkbox-component) 
> fix(checkbox): [EMU-4092] update vertical padding

- src/index.tsx
- src/lib/components/input/radio/index.stories.tsx
- src/lib/components/input/radio/index.test.tsx
- src/lib/components/input/radio/index.tsx
- src/lib/components/input/radio/styles.module.scss
- src/lib/index.tsx
- src/lib/scss/private/components/_input.scss
This PR adds the Radio component.
Check the [radio story](http://localhost:9009/?path=/docs/jsx-inputs-radio--radio-story).
> feat(radio): Add Radio component

- src/lib/components/input/checkbox/index.stories.tsx
- src/lib/components/input/checkbox/index.tsx
- src/lib/components/input/checkbox/styles.module.scss
This PR updates the checkbox component:
- adds a bordered prop allowing to have a checkbox without the bordered label:
- fixes the wide prop, making it full width when wide is true. Fixed wide pixel widths should be defined in usage, not at the design system level:
**Before**
**After**
> fix(checkbox): Add bordered prop and fix wide true size

- src/lib/components/input/checkbox/index.stories.tsx
- src/lib/components/input/checkbox/index.tsx
Refactor checkbox to use classnames object instead of string, no visible changes apart from prop usage.
> refactor(checkbox): Refactor checkbox to use classnames object

- src/index.tsx
- src/lib/components/spinner/index.stories.tsx
- src/lib/components/spinner/index.test.tsx
- src/lib/components/spinner/index.tsx
- src/lib/index.tsx
1. Creates a spinner React-based component using classes from the CSS version.
Solves:
[EMU-6599](https://linear.app/feather-insurance/issue/EMU-6599/create-spinner-component)
In the new Spinner component within the JSX section of Dirty Swan, try updating the size property using the dropdown menu in the Docs. The spinner size should increase or decrease based on your selection.
> feat(spinner): [EMU-6599] add spinner component

- src/lib/components/autocompleteAddress/index.test.tsx
- src/lib/components/autocompleteAddress/index.tsx
1. Replaces the `<span>` element with a `<button>`
2. Adds additional styling to the button for it to align with the original design
3. Updates to lowercase the first letter of the button copy in English - both in JSX and in the test file (in German it should stay uppercase)
Solves:
[EMU-5932](https://linear.app/feather-insurance/issue/EMU-5932/address-autocomplete-component-make-enter-address-manually-accessible)
In the JSX/AutocompleteAddress component.
> fix(address-autocomplete): [EMU-5932] make “enter address manually" accessible

- src/lib/components/multiDropzone/index.test.tsx
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/style.module.scss
1. Add a `label` associated to the `input` to upload a file
2. Update the label style (display) to maintain current layout
3. Add a test to check that the label text and the input are connected (which in a second stage could be used to refactor the tests that use `data-testid`)
To make the component more testable (as mentioned above) and accessible. 
Solves:
[EMU-5919](https://linear.app/feather-insurance/issue/EMU-5919/add-label-to-multidropzone-component)
You can run the test with the title "Copy text should associate input with its label".
> fix(multidropzone): [EMU-5919] add label to multidropzone component

- src/lib/components/icon/IconWrapper/IconWrapper.tsx
- src/lib/components/icon/IconWrapper/styles.module.scss
Icons paths were not centered withing SVG causing a slight disalignment:
**Before:**
**After:**
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> fix(icon): Fix icon wrapper not centering SVG

- src/lib/components/icon/IconWrapper/styles.module.scss
Replaces/reverts icon padding with margin as it was changed by mistake on the previous release.
> fix(icon): Replace padding with margin

- src/lib/components/cards/cardWithLeftIcon/index.tsx
- src/lib/components/cards/cardWithTopLeftIcon/index.tsx
This PR updates the `<CardWithLeftIcon />` and `<CardWithTopLeftIcon />` components to use a `div` to wrap children.
In order to provide `p` tags and other more flexible content to the card and not get invalid HTML
Solves:
EMU-6678
No visual changes
No visual changes
No new media
> fix(card): use div to wrap children

- src/lib/components/autocompleteAddress/index.stories.tsx
- src/lib/components/autocompleteAddress/index.tsx
1. This PR removes the `onAddressChange` callback from the `useEffect` to prevent an infinite loop when `address` prop is not provided.
2. It adds the `name` attribute to the inputs to better improve a11y
3. It provides an `inputProps` prop in order to modify the `name` attribute and any other future values we seem necessary in the future
4. It also reformats the AutocompleteAddress story
Solves:
EMU-6719
1. To test this, you have to modify the `AutocompleteAddressStory` function and remove the address prop:
```tsx
return (
<AutocompleteAddress
// address={address}
apiKey={apiKey}
manualAddressEntryTexts={manualAddressEntryTexts}
onAddressChange={handleOnAddressChange}
placeholders={placeholders}
/>
);
```
2. Go go the storypage on Storybook and enter an address
6. The autocomplete should …
> fix(address): prevent infinite loop when initial address is not provided

- src/lib/components/multiDropzone/UploadFileCell/index.tsx
- src/lib/components/multiDropzone/UploadFileCell/style.module.scss
- src/lib/components/multiDropzone/index.stories.tsx
- src/lib/components/multiDropzone/index.tsx
- Removes on removeFile icon if there isnt a remove file function passed.
- Fixes file uploader cell with large names
**Before:**
**After:**
Solves:
EMU-6747
> fix(uploader): [EMU-6747] Fix file uploader cell with large names

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/bottomModal/style.module.scss
Fix unwantedBottomModal scrolling on safari.
Open [modal story](http://localhost:9009/?path=/story/jsx-modals--bottom-or-regular-modal-story) on safari and shrink the window to make sure it shows the bottom modal. Observe the behaviour below:
**Before:**
https://github.com/getPopsure/dirty-swan/assets/4015038/47e37a94-edb8-4b61-8b9f-4caefd4731ab
**After:**
https://github.com/getPopsure/dirty-swan/assets/4015038/433854c8-98ba-43cf-9d11-7af5d72bd71f
Solves:
EMU-6739
> fix(modal): [EMU-6739] Fix BottomModal scrolling on safari

- src/lib/components/input/checkbox/index.test.tsx
- src/lib/components/input/checkbox/index.tsx
- src/lib/components/input/radio/index.test.tsx
- src/lib/components/input/radio/index.tsx
- Updates the type of the `options` prop used by the Radio and Checkbox component to render the input label, so that it doesn't only accept strings but the broader `ReactNode`
- Adds a test per component to check the label is rendered when we pass it in HTML format
Solves:
[STO-6165](https://linear.app/feather-insurance/issue/STO-6165/update-title-type-for-ds-radio-and-checkbox-input-components)
Run storybook and go through the radio and checkbox component stories to check they still render correctly.
> refactor(input): [STO-6165] update type for checkbox and radio options

- src/lib/components/input/toggle/index.stories.tsx
- src/lib/components/input/toggle/index.tsx
This PR adds the disabled state to Toggle component.
Run storybook and[ check Toggle component story.](http://localhost:9009/?path=/docs/jsx-inputs-checkbox--checkbox-story)
> fix(toggle): Add disabled state to Toggle component

- package.json
- src/index.tsx
- src/lib/components/toast/index.stories.tsx
- src/lib/components/toast/index.test.tsx
- src/lib/components/toast/index.tsx
- src/lib/components/toast/style.module.scss
- src/lib/index.tsx
- yarn.lock
This PR adds the Toaster component and toast util. Under the hood is using react-hot-toast that will replace in-app usages of `react-toastify`. The main reason for changing libraries is because this one is more than half of the size providing the same features we need.
Visit [Toast story](http://localhost:9009/?path=/docs/jsx-toast--toast-story)
[Figma link](https://www.figma.com/file/MKs4cbojdVOBKUxv7okb93/Dirty-Swan-Design-System?node-id=3%3A461&mode=dev)
**Screenshots:**
tal
> feat(toast): Add toast component/util

- src/lib/components/input/radio/index.stories.tsx
- src/lib/components/input/radio/index.tsx
Add prop to allow inline icon option to custom icon:
Run storybook and go to [Radio stories](http://localhost:9009/?path=/docs/jsx-inputs-radio--radio-story).
> fix(radio): Add prop to allow inline icon option to custom icon

- src/lib/components/card/index.stories.tsx
- src/lib/components/card/index.tsx
- src/lib/components/card/style.module.scss
- src/lib/models/styles.ts
- src/lib/scss/public/shadows.scss
This PR adds the new Card component.
Run storybook and go to [Card story](http://localhost:9009/?path=/docs/jsx-card--card-story).
**Preview:**
> feat(card): Add Card component

- src/lib/components/toast/index.stories.tsx
- src/lib/components/toast/index.tsx
- src/lib/components/toast/style.module.scss
This PR updates some of the toast styles after syncing with the design team.
**Before:**
**After:**
> refactor(toast): Update toast styles

- src/index.tsx
- src/lib/index.tsx
- src/lib/util/images/index.ts
This PR removes `as const` from image assets as they are breaking private-signup. This still allows autocompletion from types and we can still use `IllustrationKeys` types.
This PR also adds missing cards exports.
> fix(images): Fix images types and add missing card exports

- src/lib/components/multiDropzone/index.test.tsx
- src/lib/components/multiDropzone/index.tsx
If clicking on the `Choose file or drag & drop` label on a safari browser, the upload isn't triggered.
Behaviour [can be reproduced here](http://dirtyswan.design/?path=/docs/jsx-multidropzone--multi-dropzone-story).
This seems to be caused by the fact that we are triggering our own id while react-dropzone creates its own input reference inside.
> fix(multi-dropzone): Fix MultiDropzone not uploading when clicking on label

- src/lib/components/input/currency/index.tsx
- src/lib/components/input/currency/input.stories.tsx
Update Currency input to always return a number, even if empty.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> fix(currency-input): Fix currency input type to not allow null

- src/lib/components/card/index.tsx
- src/lib/components/card/style.module.scss
1. It removes an extra background when the `Card` component is rendered as button:
| Before | After |
|--------|--------|
| ![image](https://github.com/getPopsure/dirty-swan/assets/9904702/c9c7831f-fcad-4380-bf00-27adc8f183a0) | ![image](https://github.com/getPopsure/dirty-swan/assets/9904702/4cd854b8-a35f-4813-bc42-f49865ccebe0) |
2. It introduces the `buttonWrapper` classname to allow passing styles to this button component.
To give the card component more flexibility
Solves:
EMU-6959
You can check the [new updated story on Storybook](http://localhost:9009/?path=/story/jsx-card--card-with-on-click-action)
> refactor(card): [EMU-6959] add custom button styles and remove button bg

- src/lib/components/icon/IconWrapper/IconWrapper.tsx
This PR adds a min-width property to icon wrapper preventing icons from shrinking below their width on some layout definitions. 
When setting icons on layouts (like flex), sometimes content shrinks under the minimum wanted width, one example being the multi drop zone component:
**Before:**
**After:**
Solves:
EMU-7000
> fix(icon): [EMU-7000] Fix icons shrinking

- src/lib/components/card/index.tsx
- src/lib/components/card/style.module.scss
This PR fixes:
- card action action which now allows to use falsy values to not render it (e.g. `<Card actionIcon={null} />`)
- fixes card sizes that were differently if it was an action card, with and without action icon.
Solves:
EMU-7042
**Before:**
**After:**
Run storybook and check the [Card stories](http://localhost:9009/?path=/docs/jsx-card--card-story).
> fix(card): [EMU-7042] Add falsy value option for actionIcon and fix actionable card sizes

- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
This PR fixes the comparison table not re-growing in some edge cases (sudden resizes like visual regression tests).
**Before:**
https://github.com/getPopsure/dirty-swan/assets/4015038/b5b7e050-899b-46f0-8842-0b77c6d6a9ee
**After:**
https://github.com/getPopsure/dirty-swan/assets/4015038/0b83c546-9bc3-4575-ae81-27a6b14727d1
> fix(comparison-table): Fix comparison table not growing

- src/lib/components/input/radio/index.stories.tsx
- src/lib/components/input/radio/index.test.tsx
- src/lib/components/input/radio/index.tsx
- src/lib/scss/private/components/_input.scss
Allows making the DS radio input and corresponding label not clickable by leveraging the native `disabled` attribute.
https://github.com/getPopsure/dirty-swan/assets/113006001/f13b3f00-8c68-435e-bb91-86dd9c562d8e
The new Dental quote screen needs to be updated to improve the discoverability of tooth replacement coverage. For that, we need to be able to disable the radio inputs based on the selected plan - this option is currently not available in DS. 
-> [Design on Figma](https://www.figma.com/file/RTKZdSPByXcWDCioyo6BeE/Sign-Ups?type=design&node-id=35714-24696&mode=design&t=OthcHT3ZTe9NYS2V-4)
-> [Ticket](https://linear.app/feather-insurance/issue/STO-6621/improve-discoverability-of-tooth-replacement-coverage)
Solves:
[STO-6632](https://linear.app/feather-insurance/issue/STO-6632/update-t …
> feat(radio-component): [STO-6632] add support for disabling radio input

- src/lib/components/toast/index.stories.tsx
- src/lib/components/toast/index.tsx
This PR adds classnames prop to Toaster component which allows for a generic customisation of both toast and toast wrapper.
In some cases, consumers of the design system might want to pull the toast down or update some of the generic styles.
Solves:
EMU-7256
Run storybook and add classnames to see the differences:
> refactor(toaster): Add toaster classnames

- src/index.tsx
- src/lib/components/card/index.stories.tsx
- src/lib/components/card/index.tsx
- src/lib/index.tsx
This PR:
- Exports missing `CardsProps` and `IconWrapperProps`,
- Adds `showActionAction` prop to allow always showing actionIcon, useful for cases where properties other than onClick should show the icon:
On storybook, turn `showActionIcon` to true.
> fix(card): Allow always setting action icon

- src/lib/components/card/index.stories.tsx
- src/lib/components/card/index.tsx
- src/lib/components/card/style.module.scss
This PR adds the `as` prop to Card component allowing it to be rendered as other components.
This is specially useful if we want to use `a`, `button` or react-router `Link` component props without having to wrap the component in those elements (which allows to make use of hover, focus and related states).
Run storybook and [go to stories card, to the `Card as other components` story](http://localhost:9009/?path=/docs/jsx-card--card-story#card-as-other-components).
> feat(card): Add polymorphic as prop support to Card component

- src/lib/components/card/index.tsx
Fixes and cleans CardProps polymorphic generics that were throwing a TS error when used as external objects like:
```
const Foo = () => {
const props = {
as: Link,
to: '/'
};
return (
<Card {...props} />
);
}
```
Now fixed and working as expected.
> fix(card): Fix and clean card polymorphic generics

- src/lib/components/button/index.tsx
- src/lib/scss/private/components/_buttons.scss
This PR fixes btn-secondary/textColor not loading loading correctly.
**After (before it was just showing a white screen)**
> fix(button): Fix btn-secondary/textColor loading not showing correctly

- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
Replaced `ComparisonTable` `useLayoutEffect` which doesn't have an effect on server side, with `useEffect`. This will prevent website hydration error.
Solves:
STO-6814
> refactor(comparison): replaced useLayoutEffect with useEffect

- src/lib/components/comparisonTable/components/TableInfoButton/index.tsx
- src/lib/components/comparisonTable/components/TableInfoButton/style.module.scss
This PR increases the contrast ratio between TabInfoButton and background as user testing showed that it's really hard to see.
Solves:
EMU-7334
- [xw] Edge
> fix(TabInfoButton): [EMU-7334] Increase contrast

- src/lib/components/input/iban/index.tsx
- src/lib/components/input/index.tsx
- src/lib/components/input/input.stories.tsx
- src/lib/components/input/stories/config.ts
- src/lib/components/input/style.module.scss
This PR implements the `labelInsideInput` prop that allows the following input styles:
Solves:
SIDE-134
Visit [Input story](http://localhost:9009/?path=/docs/jsx-inputs-input--input-story) and toggle `labelInsideInput` prop to true.
> refactor(input): [SIDE-134] Implement label inside input

- src/lib/components/multiDropzone/index.stories.tsx
- src/lib/components/multiDropzone/index.test.tsx
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/types.ts
- src/lib/components/multiDropzone/utils/index.test.ts
- src/lib/components/multiDropzone/utils/index.ts
Updates `MultiDropzone` component to:
- have default accept type 
- have available video group types
- minor style fixes and message copy updates.
Solves:
SIDE-7
> refactor(multidropzone): [SIDE-7] Update MultiDropzone component to have default accept type

- src/lib/components/dateSelector/components/Calendar.tsx
- src/lib/components/dateSelector/index.test.tsx
- src/lib/components/dateSelector/index.tsx
DateSelector component updates:
- Moves tests to use `getByLabelText` instead of `getByTestId` (but still keeps `data-testid` as it can be useful for app testing)
- Adds additional validation to calendar component on clicking
- Allows configuring input props
> refactor(date-selector): DateSelector component updates

- src/lib/components/dateSelector/index.test.tsx
- src/lib/components/dateSelector/index.tsx
Only validates/shows error message after a date has been completed once:
Adds specific error messages for year boundaries errors:
> refactor(date-selector): Improve validation handling

- package.json
- src/lib/components/comparisonTable/components/TableArrows/index.tsx
- src/lib/components/comparisonTable/components/TableArrows/style.module.scss
- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
- src/lib/components/comparisonTable/index.tsx
- yarn.lock
This PR fixes an issue when toggling details on then off, where the scrollContainerRef would get lost.
This is accomplished by 2 things:
1. Using the new prop "InnerRef" that [can finally be used to get the ref to the child component again](https://github.com/okonet/react-scroll-sync/pull/90) inside a `ScrollSyncPane`. This way a consistent ref is retained.
2. Removing the "disabled" state from TableArrows as it was somehow messing with the refs for some unknown reason.
Before:
https://github.com/getPopsure/dirty-swan/assets/13664983/eedcc601-1a37-4141-8185-908210c4fddc
After:
https://github.com/getPopsure/dirty-swan/assets/13664983/2689eb5e-8d0a-4e89-9b92-fe57a47981eb
On a mobile view, navigate to the very last item, then toggle details on, then off. Try to navigate the items again. It …
> fix(CoverageTable): [EPIC-137] Fix details toggle messing up refs

- src/lib/components/cards/card/index.stories.tsx
- src/lib/components/cards/card/index.tsx
This PR adds the `verticalAlignment` prop to Card component.
**Preview:**
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> refactor(card): Add verticalAlignment prop to Card component

- src/lib/components/modal/bottomModal/img/close.svg
- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/bottomModal/style.module.scss
- src/lib/components/modal/genericModal/index.tsx
- src/lib/components/modal/genericModal/style.module.scss
- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/index.stories.tsx
- src/lib/components/modal/index.ts
- src/lib/components/modal/regularModal/img/close.svg
- src/lib/components/modal/regularModal/index.tsx
- src/lib/components/modal/regularModal/style.module.scss
Refactors and cleans the modals that now:
- have a `footer` prop to add a fixed footer
- reorganised and share most of the code between regular and bottom modal
- removed lots of duplicated code by the doing the above one
- modal body is now scrollable and not the whole modal
- header and footer are sticky with the bottom border of the modal header only showing on scroll
- all styling is now done using CSS instead of JS.
> refactor(modal): Refactor Modal and add modal footer

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/bottomModal/style.module.scss
- src/lib/components/modal/genericModal/index.tsx
- src/lib/components/modal/genericModal/style.module.scss
This PR adds fixes to the below modal issues:
- Close button aligning to the left if there is no title
- BottomModal padding bottom needs to be applied to body, not container
- Footer border was showing even if there was no footer
> fix(modal): Add modal fixes

- src/lib/components/modal/genericModal/style.module.scss
Update Modal close button styles to not have any padding.
> fix(modal): Update Modal close button styles

- .github/workflows/deploy.yaml
This PR removes the hardcoded v16 node version that is now not supported by storybook anymore.
> ci(deploy): Remove hardcoded v16 node version

- .github/workflows/deploy.yaml
- package.json
Replaces `storybook-to-ghpages` with `github-actions-storybook-to-github-pages` for deploying storybook to GH pages.
`storybook-to-ghpages` is now deprecated and doesn't work with storybook v8+.
> ci(deploy): Upgrade to use github-actions-storybook-to-github-pages

- .github/workflows/deploy.yaml
Add correct permissions according to package documentation:
https://github.com/bitovi/github-actions-storybook-to-github-pages
> ci(deploy): Add correct permissions to deploy action

- src/lib/components/comparisonTable/hooks/useComparisonTable.ts
- src/lib/components/comparisonTable/index.mdx
- src/lib/components/comparisonTable/index.tsx
This PR reverts back to the old workaround that had a bug when you opened and then closed via "Hide details" button where the TableArrows stopped working.
To get rid of the error the forced scroll on the closing the details was removed.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> fix(comparisonTable): [NoTicket] Use old workaround again and remove scroll

- src/lib/components/accordion/index.stories.tsx
- src/lib/components/accordion/index.tsx
- src/lib/components/accordion/style.module.scss
- src/lib/components/cards/card/index.tsx
- src/lib/components/cards/card/style.module.scss
This PR adds the `Accordion` component and does minimal changes to `Card` component for improved rewriting of styles.
Run storybook book and visit [Accordion story page](http://localhost:9009/?path=/docs/jsx-accordion--accordion-story).
**Preview:**
https://github.com/getPopsure/dirty-swan/assets/4015038/7d5a210f-e6f4-41f0-93eb-a95f91b362bb
> feat(accordion): Add Accordion component

- src/lib/components/accordion/index.tsx
- src/lib/components/accordion/style.module.scss
This PR makes minor accordion adjustments to styles after syncing with design.
Run storybook and [visit Accordion story](http://localhost:9009/?path=/docs/jsx-accordion--docs)
**Before:**
**After:**
> fix(accordion): Update accordion item styles

- src/lib/components/cards/card/index.tsx
This PR adds the missing border-radius on Card component.
Run storybook and visit [Card story](http://localhost:9009/?path=/docs/jsx-cards-card--docs).
> fix(card): Add missing border-radius on Card

- src/lib/components/modal/genericModal/style.module.scss
Increase modal z-index value to 1000 to make sure it is above other UI elements.
> refactor(modal): Increase modal z-index value

- src/lib/components/comparisonTable/index.stories.tsx
- src/lib/components/comparisonTable/index.tsx
This PR updates the `ComparisonTable` to have the `hideScrollBarsMobile` default to true.
Solves:
SIDE-179
**Before:**
**After:**
> refactor(comparison-table): [SIDE-179] Make hideScrollBarsMobile prop default to true

- src/lib/components/cards/infoCard/index.tsx
Sets the title tag of the `InfoCard` component to `h3` instead of `div`. 
- We're updating our website LP heading hierarchy for SEO reasons ([ticket](https://linear.app/feather-insurance/issue/SIDE-384/update-heading-tag-in-infocard-component) - [Figma](https://www.figma.com/design/5NkA1vw4SULFB8DciXBqaU/Untitled?node-id=0-6081&t=YhzBgNPtryiPUK4U-0))
- In the `Card` component the title is already set as h3. 
Solves:
[SIDE-384](https://linear.app/feather-insurance/issue/SIDE-384/update-heading-tag-in-infocard-component)
> feat(card): [SIDE-384] update InfoCard heading tag

- src/lib/components/table/components/TableCell/TableCell.module.scss
- src/lib/components/table/components/TableControls/TableControls.module.scss
Styling fixes to Table buttons:
- Fixes button paddings
- Increases zIndex to mobile sticky header
> fix(table): Styling fixes to Table buttons

- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableCell/TableCell.test.tsx
- src/lib/components/table/utils/useTableNavigation/useTableNavigation.test.tsx
- src/lib/components/table/utils/useTableNavigation/useTableNavigation.ts
This PR fixes the `useTableNavigation` hook and cleans warning messages from table test files.
Shortly, width of a cell is container width divided by two (because we're forcing the cell to be 50% of the screen) instead of containerWidth divided by the amount of columns.
> fix(table): Fix useTableNavigation hook

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/Table.test.tsx
- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.stories.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.module.scss
- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.stories.tsx
- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.stories.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
- src/lib/components/table/components/TableCell/TableCell.test.tsx
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.test.tsx
- src/lib/components/table/components/TableSection/TableSection.test.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
- src/lib/components/table/types.ts
This PR renames the cell properties again to make working with them easier.
It also introduces a type guard for `BaseCell` to simplify the code in sections where this is needed.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> refactor(table): [NoTicket] Rename fields again

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.module.scss
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.stories.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.stories.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
This PR implements these last minute changes:
* Adjust positioning of (i) icon
* Add ability to hide progress bar
* Add icon prop to CTA Cell
Solves:
SIDE-411
> feat(table): [SIDE-411] Last minute changes

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/Table.test.tsx
- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
- src/lib/components/table/components/TableCell/TableCell.test.tsx
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
- src/lib/components/table/types.ts
This PR adds the ability to replace cell props. Only cells affected by changes to the cellReplacements will be rerendered.
https://github.com/user-attachments/assets/953202d6-9ced-49f5-b821-b273aeb6d1ba
Solves:
SIDE-412
> feat(table): [SIDE-412] Add ability to replace cell props

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.module.scss
- src/lib/components/table/components/TableCell/CardCell/CardCell.stories.tsx
- src/lib/components/table/components/TableCell/CardCell/CardCell.tsx
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
- src/lib/components/table/types.ts
This PR adds the hideColumns property that allows hiding a column by prop setting.
This PR adds the Card Cell variant of cell rendering.
This PR adds minor fixes to styles breaking on website.
> feat(table): Add Card Cell and hideColumns property

- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
- src/lib/components/table/components/TableCell/CardCell/CardCell.tsx
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
- src/lib/components/table/types.ts
This PR cleans up and fixes some types.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> refactor(table): [NoTicket] Fix and clean up types

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/Table.test.tsx
- src/lib/components/table/Table.tsx
- src/lib/components/table/components/IconRenderer/IconRenderer.tsx
- src/lib/components/table/components/TableCell/CTACell/CTACell.tsx
- src/lib/components/table/components/TableCell/CardCell/CardCell.tsx
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
This PR adds support for icon urls and custom image components.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> feat(table): [NoTicket] Support icon urls

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/Table.tsx
Add modalContentRenderer prop to render modal content using a custom function.
Solves:
STO-XXX
EMU-XXX
RVN-XXX
> refactor(table): Add modalContentRenderer prop

- src/lib/components/table/components/TableCell/ButtonCell/ButtonCell.module.scss
- src/lib/components/table/components/TableContents/Collapsible.module.scss
- src/lib/components/table/components/TableContents/Collapsible.tsx
- src/lib/components/table/components/TableContents/TableContents.test.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
- src/setupTests.js
This PR fixes the Collapsible component by replacing react-animate-height with a custom implementation.
This retains the sticky positioning of items while animating smoothly even on mobile.
https://github.com/user-attachments/assets/5841c8a0-b66c-4437-913e-d923723f1721
Solves:
SIDE-431
> fix(collapsible): [SIDE-431] Use custom Collapsible implementation

- src/lib/components/table/utils/useTableNavigation/useTableNavigation.ts
Fix scroll navigation on mobile by adding a 10% increase on scroll position. This has no visible effect changes but makes sure it has some margin for error (some screens fail this by half a pixel).
> fix(table): Fix scroll navigation on mobile

- src/lib/components/table/components/TableCell/TableCell.module.scss
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
On mobile, card cells were scrollable.
**Before:**
**After:**
> fix(table): Fix table card not staying fixed

- src/lib/components/icon/assets/blog.svg
- src/lib/components/icon/icons/Blog.tsx
- src/lib/components/icon/icons/index.ts
This PR adds `BlogIcon` to the icon library.
Solves:
[EPIC-419](https://linear.app/feather-insurance/issue/EPIC-419/add-blogicon-to-ds-icon-library)
Check that `BlogIcon` is part of the library: http://localhost:9009/?path=/docs/jsx-icon-iconslist--docs 
> feat(icons): [EPIC-419] add BlogIcon to icon library

- src/lib/components/autocompleteAddress/index.tsx
Expose countryCode option so that we can render addresses that are not in germany.
> refactor(autocomplete-address): Expose countryCode option

- src/lib/components/autocompleteAddress/index.tsx
Make countryCode prop explicitly optional in AutoCompleteAddress component. It also makes it a string to match the Google Maps configuration.
> fix(address): Make countryCode prop optional in AutoCompleteAddress component

- src/lib/scss/private/components/_input.scss
This PR adds focus-visible states to radio and checkbox.
**Before:**
**After:**
> fix(a11y): Add focus-visible states to radio and checkbox

- src/lib/components/modal/genericModal/style.module.scss
Fix modal glitch with scroll bar on open/close.
**Before:**
https://github.com/user-attachments/assets/739ea49f-b378-41e0-af7b-5d1ed0e6e4ae
**After:**
https://github.com/user-attachments/assets/c6ad4f50-79fb-4328-ae22-5070675ae76e
> fix(modal): Fix modal glitch with scroll bar on open/close

- src/lib/components/comparisonTable/components/Row/style.module.scss
- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.module.scss
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
- src/lib/components/table/components/TableCell/TableCell.module.scss
- src/lib/components/table/components/TableCell/TableCell.tsx
- src/lib/components/table/components/TableContents/TableContents.tsx
Fix styles on table.
**Before/after:**
1. Fix underline styles when two lines:
2. Fix mobile header not growing over 50%:
3. Fix word not breaking when too big:
4. Decrease left spacing on table headers:
Solves:
SIDE-535
SIDE-536
SIDE-537
> fix(table): [SIDE-535][SIDE-536][SIDE-537] Fix styles on table

- src/lib/components/button/index.stories.tsx
- src/lib/components/button/index.tsx
- src/lib/components/cards/card/index.tsx
- src/lib/components/table/Table.tsx
Make button a polymorphic component which means you can now pass the `as` prop and define the component as a nextjs or react-router `Link` (or other frameworks) or `a` HTML tag.
> refactor(button): Make button a polymorphic component

- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.module.scss
Show header title (first cell in first row) on mobile screens
Solves:
SIDE-553
**Before:**
**After:**
> refactor(table): [SIDE-553] Show header title (first cell in first row) on mobile screens

- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
Update BIG_WITH_UNDERLINE to be an h2.
> refactor(table): Update BIG_WITH_UNDERLINE to be an h2

- src/lib/components/button/index.stories.tsx
- src/lib/components/button/index.tsx
- src/lib/scss/private/components/_buttons.scss
This PR introduces a new button variant (`filledBlack`) -> [Figma](https://www.figma.com/design/MKs4cbojdVOBKUxv7okb93/Dirty-Swan-Design-System?node-id=17167-87383&t=O1Hc6mhD7LNMUBMU-4)
The Design team is introducing this variant in our system. 
We need to implement this variant with high priority in the B2B website banner (as a start). 
Solves:
SIDE-647
You can check the new button variant locally [here](http://localhost:9009/?path=/story/jsx-button--button-variants), also for the hover, focus, and disabled state. 
> feat(button): [SIDE-647] introduce the `filledBlack` variant

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.module.scss
- src/lib/components/table/components/TableCell/BaseCell/BaseCell.tsx
This PR updates the position of table's info button component, so it doesn't get pushed whenever the table cell has long content.
**Before**
**After**
> refactor(table): update info button positioning

- src/lib/components/autocompleteAddress/index.tsx
Fix AutoCompleteAddress checking google initialised state. Since this was just checking if google was initialised, it could break if there are other google APIs present on the same codebase also using the `window.google` namespace.
> fix(google-check): Fix AutoCompleteAddress checking google

- package.json
- src/index.tsx
- src/lib/components/modal/fullScreenModal/index.tsx
- src/lib/components/modal/fullScreenModal/style.module.scss
- src/lib/components/modal/genericModal/index.tsx
- src/lib/components/modal/hooks/useOnClose.ts
- src/lib/components/modal/index.stories.tsx
- src/lib/components/modal/index.ts
- src/lib/hooks/useEscapeKey.ts
- src/lib/hooks/useFocusWithin.ts
- src/lib/index.tsx
- yarn.lock
This PR introduces some accessibility-related updates.
**Modal:**
- We introduce a full-screen modal variant, which will be used for the website navigation menu on mobile
- We enable using the modal with the escape key with the focus going back to the element that opened it
- We use the package `react-focus-lock` to lock focus within the modal when open.
**Hooks:**
We also move to DirtySwan two hooks we already use on the website (`useFocusWithin` and `useEscapeKey`), so they can be shared across repos. 
Go through our modal variants and check the following behaviors:
- Modal can be opened with space key
- Modal can be closed with esc key and the focus will go back to the element that opened it
- When open and tabbing through, the focus will remain within the focusable elements of the …
> feat(accessibility): [NoTicket] update modal and hooks

- src/lib/components/modal/bottomModal/index.tsx
- src/lib/components/modal/fullScreenModal/index.tsx
- src/lib/components/modal/genericModal/index.tsx
- src/lib/components/modal/index.stories.tsx
- src/lib/components/modal/index.ts
- src/lib/components/modal/regularModal/index.tsx
This PR includes `classNames` in the modal components props to allow customizing modal styles. 
Solves: NoTicket
> feat(modal): [NoTicket] include classNames in modal customization

- src/lib/components/table/Table.module.scss
- src/lib/components/table/Table.tsx
> fix(table): Fix modal content overflowing on mobile

- src/lib/hooks/useMediaQuery.ts
Allow useMediaQuery with undefined window (e.g. when using Next.JS)
> fix(use-media-query): Allow useMediaQuery with undefined window

- src/lib/components/accordion/index.stories.tsx
- src/lib/components/accordion/index.tsx
Add support to custom render answer, allowing to add, as an example, custom markdown or rich text components to render the content.
> refactor(accordion): Add support to custom render answer

- src/lib/components/table/Table.module.scss
- src/lib/components/table/Table.tsx
- src/lib/components/table/components/TableControls/TableControls.module.scss
- src/lib/components/table/components/TableControls/TableControls.tsx
When scrolling using an anchor (`#anchor` on the URL) and `id="anchor"` on the HTML wrapper component, the component was scrolling including the header amount. This PR fixes that.
**Before:**
https://github.com/user-attachments/assets/bf78d7d7-3c65-42b3-9ac5-faefe505b81b
**After:**
https://github.com/user-attachments/assets/4d78f12a-a50c-46ac-afcd-fc3448d2eb82
Solves:
SIDE-1316
> fix(table): [SIDE-1316] Fix first row hidden on scrolling to  anchor

- src/lib/components/table/Table.stories.tsx
- src/lib/components/table/components/TableSection/TableSection.tsx
- src/lib/components/table/types.ts
1. Add support for custom modal titles ([example on the operations row](http://localhost:9009/?path=/story/jsx-table--table-story))
2. Makes the default modal title show from row header instead of column header. As per the example below, we would now show `Select a plan` instead of `standard` if there was a modal on the second row.
Solves:
SIDE-1351
[Run storybook](https://dirtyswan.design/?path=/story/jsx-table--table-story) and update the table data to include `modalTitle`
> refactor(table): Add support for custom modal titles

- src/lib/components/modal/bottomModal/index.tsx
1. Now using H2 mobile, with the BottomModal, by setting the titleSize to default
Solves:
SIDE-604
Enter the BottomModal that is used in the mobile and it will show H2 insted of H4.
> fix(bottommodal.tsx): [SIDE-604] Use h2 header on mobile

- src/lib/components/autocompleteAddress/index.tsx
Revert being able to switch back to search on autocomplete address
> revert(autocomplete-address): Revert being able to switch back to search

- src/index.tsx
- src/lib/index.tsx
This PR exports the `useOnClickOutside` hook to make it available for import. The hook will be used in the `affiliates-dashboard` repo
> feat(hooks): [NO-TICKET] export the `useOnClickOutside` hook

- src/lib/components/input/checkbox/index.tsx
Updates the default legend text for a checkbox group in case the field there's only one option.
Now, if no custom legend text is provided and the radio field has only one option, the screen reader would read: `'Select one or more options'`.
Solves:
NoTicket
> fix(checkbox): [NoTicket] update default legend text when only one option

- src/lib/components/multiDropzone/UploadFileCell/index.tsx
- src/lib/components/multiDropzone/UploadFileCell/style.module.scss
- src/lib/components/multiDropzone/index.tsx
- src/lib/components/multiDropzone/style.module.scss
- src/lib/components/multiDropzone/utils/index.test.ts
- src/lib/components/multiDropzone/utils/index.ts
Updates Multidropzone component
1. Adding focus state for the input
2. Adding focus states for the view and delete buttons
3. Adding a section with an upload status message which will be read by screen readers.
Solves:
SIDE-1445
Use the multidropzone component with a keyboard and screen reader:
- you should see focus states for the input and the view and delete buttons
- the screen reader should read aloud if uploading a file was successful or failed.
> refactor(multidropzone): [SIDE-1445] add focus states and aria-live

- src/lib/components/input/index.tsx
1. This PR fixes how we set `aria-errormessage` in the Input component. 
From https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-errormessage:
> There are two attributes you need to use: set [aria-invalid="true"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-invalid) to define the object as being in an error state, then add the aria-errormessage attribute with the value being the id of the element (or elements) containing the error message text for that object.
> fix(input): [NoTicket] fix aria-errormessage usage

- src/lib/components/input/checkbox/styles.module.scss
- src/lib/components/input/radio/styles.module.scss
1. Removes the styling reset from the <fieldset> element in the radio and checkbox components. 
The reset is already applied in src/lib/scss/private/_reset.scss and ends up conflicting with custom styling using `classNamesObj?.container`.
Solves:
NoTicket
> fix(radio-checkbox): [NoTicket] remove fieldset style reset

- src/lib/components/input/style.module.scss
This PR fixes an issue where the input value is misaligned if no placeholder is set and the label is shown inside the input.
> fix(input): [NoTicket] Fix value alignment with inside label

- src/lib/components/badge/index.tsx
- src/lib/scss/public/colors/default.scss
- src/lib/scss/public/demo.tsx
Update auxiliary colors.
**Preview (Before/After):**
> chore(colors): Update auxiliary colors

- src/lib/components/autocompleteAddress/index.tsx
- src/lib/components/autocompleteAddress/style.module.scss
- src/lib/scss/private/components/_buttons.scss
- src/lib/scss/private/components/_input.scss
This PR fixes: 
- autocomplete address loading state:
- and radio checbkox styles that had the wrong border color
- button disabled state opacity
> fix(rebranding): Fix autocomplete address, disabled button and radio/checkbox styles
